name: NPM Publish

on:
    workflow_call:
        inputs:
            registryUrl:
                type: string
                required: true
        secrets:
            token:
                description: "Access Token"
                required: true

permissions: write-all

jobs:
    Publish:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Extract Version from Tag
                id: getVersion
                run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    registry-url: "https://${{ inputs.registryUrl }}"
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.token }}

            -   name: Setup .npmrc
                run: |
                    echo "//${{ inputs.registryUrl }}:_authToken=${{ secrets.token }}" > .npmrc
                    echo "@encoredigitalgroup:registry=https://${{ inputs.registryUrl }}" >> .npmrc

            -   name: Install NPM Dependencies
                run: npm ci

            -   name: Update Package Version
                run: npm version ${{ steps.getVersion.outputs.version }} --no-git-tag-version

            -   name: Build
                run: npm run build

            -   name: Publish to ${{ inputs.registryUrl }}
                run: npm publish --access public --no-git-checks --provenance